/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package HellBot

import HellBot.extensions.DevExtension
import HellBot.extensions.FunExtensions
import HellBot.extensions.MusicExtension
import HellBot.extensions.ReactionExtension
import dev.kord.common.entity.Snowflake
import dev.kordex.core.ExtensibleBot
import dev.kordex.core.utils.env
import HellBot.extensions.TestExtension
import dev.kord.common.entity.PresenceStatus
import dev.kordex.core.utils.envOrNull
import dev.schlaubi.lavakord.kord.lavakord
import se.michaelthelin.spotify.SpotifyApi
import se.michaelthelin.spotify.requests.authorization.client_credentials.ClientCredentialsRequest
import java.io.File

val TEST_SERVER_ID = Snowflake(
	env("TEST_SERVER").toLong()  // Get the test server ID from the env vars or a .env file
)

var spotify: SpotifyApi? = null

private val TOKEN = env("TOKEN")   // Get the bot' token from the env vars or a .env file

suspend fun main() {
	val bot = ExtensibleBot(TOKEN) {
		applicationCommands {
			defaultGuild(envOrNull("TEST_SERVER"))
		}

		presence {
			status= PresenceStatus.DoNotDisturb
			competing("Iemand zerge?")
		}

		chatCommands {
			defaultPrefix = "?"
			enabled = true

			prefix { default ->
				if (guildId == TEST_SERVER_ID) {
					// For the test server, we use ! as the command prefix
					"!"
				} else {
					// For other servers, we use the configured default prefix
					default
				}
			}
		}

		extensions {
			add(::MusicExtension)
			add(::DevExtension)
			add(::ReactionExtension)
			add(::FunExtensions)
		}

		if (devMode) {
			// In development mode, load any plugins from `src/main/dist/plugin` if it exists.
			plugins {
				if (File("src/main/dist/plugins").isDirectory) {
					pluginPath("src/main/dist/plugins")
				}
			}
		}
	}

	// Initialize Spotify API if the client ID and secret are provided
	if (envOrNull("SPOTIFY_CLIENT_ID") != null && envOrNull("SPOTIFY_CLIENT_SECRET") != null) {
		spotify = SpotifyApi.Builder()
			.setClientId(env("SPOTIFY_CLIENT_ID"))
			.setClientSecret(env("SPOTIFY_CLIENT_SECRET"))
			.build()

		val credRequest: ClientCredentialsRequest  = spotify!!.clientCredentials().build()
		val clientCredentials = credRequest.execute()
		spotify!!.setAccessToken(clientCredentials.accessToken)

	}

	bot.start()

}
